name: griot_urban_mobile
description: Application mobile pour le rap ivoirien.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  flutter_spinkit: ^5.1.0
  audioplayers: ^4.1.0       # Pour les effets sonores
  flutterwave: ^0.0.5        # Paiements
  provider: ^6.0.5           # Gestion d'état
  animated_text_kit: ^4.2.2   # Animations de texte
  flutter_staggered_animations: ^1.0.0  # Animations décalées

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/ninho_himra.mp3  # Extrait sonore
    - .env

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
