name: griot_urban_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Assure-toi que cette version est compatible avec ton Flutter

dependencies:
  flutter:
    sdk: flutter

  # DEBUT DES AJOUTS
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0
  # FIN DES AJOUTS

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # DEBUT DES AJOUTS
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  # FIN DES AJOUTS

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
